from widget.asset_balance_penal import AssetBalancePenal
from widget.trade_setting_penal import TradeSettingPenal
from widget.trade_history_table import TradeHistoryMonitor
from widget.about_dialog import AboutDialog
from widget.select_model_dialog import SelectModelDialog
from widget.select_account_dialog import SelectAccountDialog
from widget.model_penal import ModelPanel
from widget.trade_penal import TradePanel
from widget.main_frame import MainFrame
from widget.main_dock import MainDock
