from widget.asset_balance_penal import AssetBalancePenal
from widget.trade_setting_penal import TradeSettingPenal
from widget.trade_history_table import TradeHistoryMonitor
from widget.about_dialog import AboutDialog
from widget.select_model_dialog import SelectModelDialog
from widget.select_account_dialog import SelectAccountDialog

from widget.main_dock import MainDock
